# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OutputUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 458)


        self.umap = QtWidgets.QFrame(MainWindow)
        self.umap.setGeometry(QtCore.QRect(30, 30, 291, 231))
        self.umap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.umap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.umap.setObjectName("umapFrame")
        self.heatMap = QtWidgets.QFrame(MainWindow)
        self.heatMap.setGeometry(QtCore.QRect(350, 30, 281, 231))
        self.heatMap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.heatMap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.heatMap.setObjectName("heatMapFrame")


        self.groupBox = QtWidgets.QGroupBox(MainWindow)
        self.groupBox.setGeometry(QtCore.QRect(390, 320, 261, 131))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(140, 100, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(130, 70, 131, 21))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 70, 141, 21))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(130, 40, 87, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.checkBox.setObjectName("checkBox")


        

        # gene gene button
        self.geneGeneButton = QtWidgets.QPushButton(MainWindow)
        self.geneGeneButton.setGeometry(QtCore.QRect(30, 420, 113, 32))
        self.geneGeneButton.setObjectName("geneGeneButton")
        # self.geneGeneButton.clicked.connect(self.genePopUp(self))

        # self.geneGenePopUp = QtWidgets.QMessageBox(self.wid)

        # def genePopUp(self):
            # geneGenePopUp.show()
        #self.geneGeneButton.adjustSize()
        


        # self.scrollArea = QtWidgets.QScrollArea(MainWindow)
        # self.scrollArea.setGeometry(QtCore.QRect(40, 330, 241, 91))
        # self.scrollArea.setWidgetResizable(True)
        # self.scrollArea.setObjectName("scrollArea")

        self.dropdown = QtWidgets.QComboBox(MainWindow)
        self.dropdown.setGeometry(QtCore.QRect(30, 300, 239, 89))

        def pathwayNames(d):
            names = []
            for pathway in d.values():
                names.extend([*pathway])
            return names
        
        # for example 
        dict = {'sonia': {'brown': 'tan', 'braids': 'tired'}, 'elijah': {'black': 'blue', 'blonde': 'yawn'}, 'lucas': {'nike': 'finland', 'curly': 'sniffle'}, 'raffa': {'skate': 'fast', 'locs': 'long'}, 'amani': {'sleep': 'happy', 'work': 'sad'}}
        

        self.dropdown.addItems(pathwayNames(dict))
        self.dropdown.setObjectName("pathwayDropdown")
        # self.dropdown.setWidget(self.scrollAreaWidgetContents)


        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 239, 89))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(140, 270, 41, 16))
        self.label.setObjectName("label")


        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(460, 270, 60, 16))
        self.label_2.setObjectName("label_2")


        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(40, 310, 121, 16))
        self.label_3.setObjectName("label_3")


        self.pushButton_2 = QtWidgets.QPushButton(MainWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(152, 420, 131, 32))
        self.pushButton_2.setObjectName("pushButton_2")


        self.groupBox.raise_()
        self.umap.raise_()
        self.heatMap.raise_()
        # self.scrollArea.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton_2.raise_()
        self.geneGeneButton.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SPECTRA"))
        self.groupBox.setTitle(_translate("MainWindow", "Save Options"))
        self.pushButton.setText(_translate("MainWindow", "Save "))
        self.checkBox_4.setText(_translate("MainWindow", "SPECTRA Model"))
        self.checkBox_3.setText(_translate("MainWindow", "Umap"))
        self.checkBox_2.setText(_translate("MainWindow", "Heat map"))
        self.checkBox.setText(_translate("MainWindow", "AnnData"))
        self.label.setText(_translate("MainWindow", "Umap "))
        self.label_2.setText(_translate("MainWindow", "Heat map"))
        self.label_3.setText(_translate("MainWindow", "Umap Coloration"))
        self.pushButton_2.setText(_translate("MainWindow", "Generate Umap"))
        self.geneGeneButton.setText(_translate("MainWindow", "SPECTRA model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
